package com.sample.soap.xml.dm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathsDbServiceImplService", targetNamespace = "http://dm.xml.soap.sample.com/", wsdlLocation = "http://localhost:8080/DmOldSoapWs/services/DmService/1.0?wsdl")
public class MathsDbServiceImplService
    extends Service
{

    private final static URL MATHSDBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHSDBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MATHSDBSERVICEIMPLSERVICE_QNAME = new QName("http://dm.xml.soap.sample.com/", "MathsDbServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DmOldSoapWs/services/DmService/1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHSDBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MATHSDBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MathsDbServiceImplService() {
        super(__getWsdlLocation(), MATHSDBSERVICEIMPLSERVICE_QNAME);
    }

    public MathsDbServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHSDBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MathsDbServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MATHSDBSERVICEIMPLSERVICE_QNAME);
    }

    public MathsDbServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHSDBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MathsDbServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathsDbServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MathsDbService
     */
    @WebEndpoint(name = "MathsDbServiceImplPort")
    public MathsDbService getMathsDbServiceImplPort() {
        return super.getPort(new QName("http://dm.xml.soap.sample.com/", "MathsDbServiceImplPort"), MathsDbService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathsDbService
     */
    @WebEndpoint(name = "MathsDbServiceImplPort")
    public MathsDbService getMathsDbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dm.xml.soap.sample.com/", "MathsDbServiceImplPort"), MathsDbService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHSDBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MATHSDBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MATHSDBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
